name: CI
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn
      - name: Install project dependencies
        run: yarn --prefer-offline
      - name: Run formatter
        run: yarn check:format
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn
      - name: Install project dependencies
        run: yarn --prefer-offline
      - name: Run linter
        run: yarn check:lint
