name: Solid Renderer Pipeline
on:
  pull_request:
    branches:
      - '*'
    paths:
      - packages/renderers/solid/**
  push:
    branches:
      - main
    paths:
      - packages/renderers/solid/**
  release:
    types: [published]
    branches:
      - main
defaults:
  run:
    working-directory: packages/renderers/solid
jobs:
  solid-workflow:
    runs-on: ubuntu-latest
    name: Lib workflow
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn
      - name: Install project dependencies
        run: yarn --prefer-offline
      - name: Check bundling
        run: yarn check
        working-directory: packages/renderers/solid
      - name: Publish to NPM
        if: github.event_name == 'release'
        run: yarn npm publish
        working-directory: packages/renderers/solid
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
